### ISSUE TITLE
code is not reproducible (running it creates an error)

### ISSUE THREAD

**Issue by Lakens** [agbarnett/taxinspect#1]
Hi,

I was interested in playing around with this script. However, it seems not to run without error. Running simulate.research.world.R gives the error:
 Error in `$<-.data.frame`(`*tmp*`, cum.mistakes, value = numeric(0)) : 
  replacement has 0 rows, data has 66 
 
This might be due to the perform.communicate.R function, if I try to trace back the error. Any ideas? Is this me, or if you run the code, do you reproduce this error?
Thanks

**Comment by agbarnett** [comment]
Sorry Daniel, I've only just noticed this. You were right. I've hopefully ironed out these bugs now.
